package com.example.earthquack.storage

/**
 * The raw reply from a single rclone RPC call.
 *
 * Deliberately separate from the gomobile-generated
 * `com.example.earthquack.rclone.RcloneResult`: this is our own type, so the
 * rest of the app never depends on a class generated by a build step. It also
 * lets us normalise gomobile's `long` status down to an [Int] once, here,
 * instead of at every call site.
 *
 * @param status rclone's HTTP-style status: 200 on success, 4xx for a bad
 *   request or unknown method, 5xx for an internal failure.
 * @param output always a JSON document. On failure it is rclone's standard
 *   error envelope, so it is still parseable — never treat it as free text.
 */
data class RcloneResult(
    val status: Int,
    val output: String
) {
    /** True when rclone reported success. */
    val isSuccess: Boolean get() = status == HTTP_OK

    companion object {
        const val HTTP_OK = 200

        /** A result representing a call that never reached rclone. */
        fun failure(status: Int, output: String): RcloneResult =
            RcloneResult(status, output)
    }
}

/**
 * Thrown when an RPC call fails, carrying rclone's own error envelope.
 *
 * The envelope is preserved in [rcloneOutput] so callers that need to
 * distinguish "remote not found" from "permission denied" can parse it,
 * instead of string-matching a flattened message.
 */
class RcloneException(
    val method: String,
    val status: Int,
    val rcloneOutput: String,
    message: String
) : Exception(message)

/**
 * The three-call native surface, abstracted so the engine can be unit tested
 * on the JVM without `libgojni.so`.
 *
 * Production code uses [NativeRcloneBridge]; tests substitute a fake.
 */
interface RcloneBridge {
    /**
     * @param configPath absolute path to rclone.conf, or "" for in-memory
     *   config that is never persisted.
     */
    fun initialize(configPath: String)
    fun rpc(method: String, input: String): RcloneResult
    fun shutdown()
}
